development:
  adapter: postgresql
  encoding: unicode
  database: pavlov_development
  pool: 5

test:
  adapter: postgresql
  encoding: unicode
  database: pavlov_test
  pool: 5

production:
  adapter: postgresql
  encoding: unicode
  database: pavlov_production
  pool: 5